# Generated by Django 2.2.3 on 2019-07-10 14:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField(verbose_name='data de nascimento')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_veiculo', models.CharField(choices=[('CR', 'Carro'), ('MT', 'Moto')], default='CR', max_length=2)),
                ('nome', models.CharField(max_length=35)),
                ('marca', models.CharField(max_length=25)),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, None), django.core.validators.MaxValueValidator(9999, None)])),
                ('placa_letras', models.CharField(max_length=3)),
                ('placa_numeros', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, None), django.core.validators.MaxValueValidator(9999, None)])),
                ('observacoes', models.TextField(max_length=1500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data da viagem')),
                ('saida', models.TimeField(verbose_name='horario da saida')),
                ('retorno', models.TimeField(verbose_name='horario do retorno')),
                ('observacoes', models.TextField(max_length=1500, null=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.Motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.Veiculo')),
            ],
        ),
    ]
