# Generated by Django 2.2.3 on 2019-07-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_auto_20190710_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='retorno',
            field=models.TimeField(blank=True, null=True, verbose_name='horario do retorno'),
        ),
    ]
