# Generated by Django 2.2.4 on 2019-10-21 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField(null=True, verbose_name='data de nascimento')),
                ('observacoes', models.TextField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_veiculo', models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto')], default='Carro', max_length=5)),
                ('nome', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=40)),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, None), django.core.validators.MaxValueValidator(9999, None)])),
                ('placa', models.CharField(max_length=8)),
                ('observacoes', models.TextField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data da viagem')),
                ('saida', models.TimeField(verbose_name='horario da saida')),
                ('retorno', models.TimeField(blank=True, null=True, verbose_name='horario do retorno')),
                ('observacoes', models.TextField(blank=True, max_length=1500)),
                ('motorista', models.ForeignKey(on_delete=None, to='fleet.Motorista')),
                ('veiculo', models.ForeignKey(on_delete=None, to='fleet.Veiculo')),
            ],
        ),
    ]
