# Generated by Django 2.2.3 on 2019-07-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='data_nascimento',
            field=models.DateField(blank=True, verbose_name='data de nascimento'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='observacoes',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='observacoes',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='retorno',
            field=models.TimeField(blank=True, verbose_name='horario do retorno'),
        ),
    ]
