# Generated by Django 3.0 on 2019-12-11 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_auto_20190710_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorista',
            name='sobrenome',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='placa_letras',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='placa_numeros',
        ),
        migrations.AddField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='motorista',
            name='observacoes',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='data_nascimento',
            field=models.DateField(null=True, verbose_name='data de nascimento'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo_veiculo',
            field=models.CharField(choices=[('Carro', 'Carro'), ('Moto', 'Moto')], default='Carro', max_length=5),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='motorista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.Motorista'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='veiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.Veiculo'),
        ),
    ]
