# Generated by Django 2.2.4 on 2019-08-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_auto_20190710_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='observacoes',
            field=models.TextField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa_numeros',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='motorista',
            field=models.ForeignKey(on_delete=None, to='fleet.Motorista'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='veiculo',
            field=models.ForeignKey(on_delete=None, to='fleet.Veiculo'),
        ),
    ]
