# Generated by Django 2.2.4 on 2019-08-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_auto_20190806_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(default='123.456.789-00', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(default='ABC-1234', max_length=8),
            preserve_default=False,
        ),
    ]
