# Generated by Django 2.2.4 on 2019-08-14 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_auto_20190814_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='placa_letras',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='placa_numeros',
        ),
    ]
