# Generated by Django 2.2.4 on 2019-10-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_auto_20190814_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorista',
            name='sobrenome',
        ),
        migrations.AlterField(
            model_name='motorista',
            name='data_nascimento',
            field=models.DateField(null=True, verbose_name='data de nascimento'),
        ),
    ]
